name: Validate BCheck scripts
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout the code base
      - uses: actions/setup-java@v3
        name: Install Java
        with:
          distribution: "temurin"
          java-version: '17'      
      - name: Run the validator
        shell: pwsh
        run: |
          java -version
          .\Test-Scripts.ps1 
